#!/bin/bash
about () {
  echo "explain any bash command via mankier.com manpage API
  example $ explain 'cmd -o | ...' # one quoted command to explain it."
}
run () {
  if [ "$#" -eq 0 ]; then
    while read  -p "Command: " cmd; do
      curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols)"&q=$cmd"
    done
    echo "Bye!"
  else
    curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols)"&q=$1"
  fi
}

if [ $# -ge 1 ]; then
  run $@
else
  about
fi
